#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication topoSet -constant

cp -rp Zero 0
cp -p ZeroSRG/pointMotionU 0
runApplication surfRoughGen
cp -p Zero/pointMotionU 0
rm 0/cellMotionU

runApplication checkMesh -allGeometry -allTopology
