#!/bin/sh
cd ${0%/*} || exit 1    # Run all cases

if [ -z ${1+x} ]; then
    echo "Must enter the number of processors: e.g. Allrun 4"
    exit
fi    

cp system/controlDict.template system/controlDict
makeSTL
makeMesh
Run $1  0
reMesh  0
Run $1 20
reMesh 20
Run $1 40
reMesh 40

mv Save/[0-9]* .

# ------------------------------------------------------------------- #
