#!/bin/sh
cd ${0%/*} || exit 1    # Run all cases

if [ -z ${1+x} ]; then
    echo "Must enter the number of processors: e.g. Allrun 4"
    exit
fi    

cp system/controlDict.template system/controlDict
cp system/snappyHexMeshDict.template system/snappyHexMeshDict
./makeSTL
./makeMesh 1
./Run $1  0
./reMesh  0 0 1
./Run $1  1
./reMesh  1 0 1
./Run $1  2
./reMesh  2 0 1
./Run $1  3
./reMesh  3 0 1
./Run $1  4
./reMesh  4 0 1
./Run $1  5
./reMesh  5 0 1
./Run $1  6
./reMesh  6 0 1
./Run $1  7
./reMesh  7 0 1
./Run $1  8
./reMesh  8 0 1
./Run $1  9
./reMesh  9 0 1
./Run $1  10


mv Save/[0-9]* .

# ------------------------------------------------------------------- #
