#!/bin/sh
cd ${0%/*} || exit 1    # create mesh from stl files with snappyHex

blockMesh -dict system/box.blockMeshDict 2>&1 \
    | tee log.blockMeshBox 2>&1

surfaceFeatureExtract 2>&1 | tee log.surfaceFeatureExtract 2>&1
snappyHexMesh -overwrite 2>&1 | tee log.snappyHexMesh 2>&1

extrudeMesh 2>&1 | tee log.extrudeMesh 2>&1
transformPoints -translate '(0 0 -1)'   # transform points to 0 < z < 1/2
orderBoundaries -overwrite 2>&1 | tee log.orderBoundaries

checkMesh -allGeometry -allTopology -constant -noZero 2>&1 \
    | tee log.checkMesh 2>&1

# ------------------------------------------------------------------- #
