#!/bin/sh
cd ${0%/*} || exit 1            # additional steps for remeshing

if [ -z ${1+x} ]; then          # startTime=0 if undefined
    startTime=0
else
    startTime=$1
fi

if [ -z ${2+x} ]; then          # startTime=0 if undefined
    reIter=0
else
    reIter=$2
fi

initRef=2
lastRef=1

#echo "Debug. reIter : $reIter"
#exit 0

endTime=`cat system/controlDict | grep "endTime " \
    | awk '{print $2}' | sed -e '/;/s///'`
echo "Run started at t = $startTime and ended at t = $endTime"

#  Update controlDict for new run
diffT=$(echo $endTime - $startTime | bc)
newStartTime=$(echo $startTime + $diffT | bc)
newEndTime=$(echo $endTime + $diffT | bc)
echo "New run will start at t = $newStartTime and end at t = $newEndTime"
sed -i -e "/endTime /s/$endTime/$newEndTime/" system/controlDict
echo "controlDict updated"

./remakeSTL                       # make new stl file from latestTime

#  Save current times for later viewing
if [ $startTime -ne 0 ]; then   # remove $startTime (no data)
    writeInterval=`cat system/controlDict | grep "writeInterval " \
        | awk '{print $2}' | sed -e '/;/s///'`
    firstOutTime=$(echo $startTime + $writeInterval | bc)
    echo "Moving polyMesh from $startTime to $firstOutTime"
    mv $firstOutTime/polyMesh/points $firstOutTime/.    # tmp save
    mv $startTime/polyMesh/* $firstOutTime/polyMesh/.
    mv $firstOutTime/points  $firstOutTime/polyMesh/.   # restore
    rm -r $startTime
    echo "$StartTime deleted (no field data)"
else
    if [ -d Save ]; then
        echo "Save already exists: Exiting!"
        exit
    fi
    mkdir Save
    cp -rp system constant Save
fi
mv [0-9]* Save

# modify snappyHexMesh to make surface cell smaller
#sed -i -e "/level (/s/$($reIter+1) $($reIter+1)/$($reIter+1) $($reIter+1)/" system/snappyHexMeshDict
echo "modify snappyHexMesh:  last: $(($reIter+$lastRef))  next: $(($reIter+$initRef))"
sed -i -e "/level (/s/$(($reIter+$lastRef)) $(($reIter+$lastRef))/$(($reIter+$initRef)) $(($reIter+$initRef))/" system/snappyHexMeshDict

#  Make new mesh
./Clean
./makeMesh $3

# ------------------------------------------------------------------- #
