#!/bin/sh
cd ${0%/*} || exit 1            # run script

#  Check input params: np first then startTime
if [ -z ${1+x} ]; then          # nproc=1 if undefined
    nproc=1
else
    nproc=$1
fi

if [ -z ${2+x} ]; then          # startTime=0 if undefined
    startTime=0
else
    startTime=$2
fi
echo "Starting at t = $startTime with $np processors"

if [ ! -d "$startTime" ]; then  # create starting directory
    cp -rp Zero $startTime
    mv constant/polyMesh $startTime
fi


#  Run selection
if [ $nproc -eq 1 ]; then
    echo "Running in serial"
    dissolFoam 2>&1 | tee log.dissolFoam

else

    echo "Running in parallel with $1 processors"
    if [ ! -d "processor0" ]; then
        cat system/decomposeParDict.template \
            | sed "/sub/s//$1/" > system/decomposeParDict
        decomposePar -copyUniform 2>&1 | tee log.decompose
    fi

    mpirun -np $nproc dissolFoam -parallel 2>&1 | tee log.dissolFoam

    diff 0/C Zero/C > /dev/null 2>&1 
    if [ $? == 0 ]; then
        reconstructPar -withZero 2>&1 | tee log.reconstruct
    else
        reconstructPar -newTimes 2>&1 | tee log.reconstruct
    fi
fi

# ------------------------------------------------------------------- #
