#!/bin/sh
cd ${0%/*} || exit 1    # clean case

Clean
rm -rf Save

echo
echo "Directory cleaned: Make sure controlDict.template is up to date"

# ------------------------------------------------------------------- #
