#!/bin/sh
cd ${0%/*} || exit 1    # Generate stl from existing surface

surfaceMeshTriangulate -patches "(solubleWall)" \
    constant/triSurface/obj.stl 2>&1 \
    | tee log.surfaceMeshTriangulateObj 2>&1

surfaceTransformPoints -scale '(1 1 4)' \
    constant/triSurface/obj.stl constant/triSurface/obj.stl 2>&1 \
    | tee log.surfaceMeshTriangulateObj 2>&1
surfaceTransformPoints -translate '(0 0 -0.5)' \
    constant/triSurface/obj.stl constant/triSurface/obj.stl 2>&1 \
    | tee log.surfaceMeshTriangulateObj 2>&1


#-----------------------------------------------------------------------
