#!/bin/sh
cd ${0%/*} || exit 1

if [ ! -d "0" ]; then
    cp -rp 0org 0
fi

if [ $# -eq 0 ]; then
    echo "Running in serial"

    dissolFoam 2>&1 | tee log.run

else

    echo "Running in parallel with $1 processors"

    if [ ! -d "processor0" ]; then
        cat system/decomposeParDict.template \
            | sed "/sub/s//$1/" > system/decomposeParDict
        decomposePar -copyUniform 2>&1 | tee log.decompose
    fi

    mpirun -np $1 dissolFoam -parallel 2>&1 | tee log.run

    diff 0/C 0org/C > /dev/null 2>&1 
    if [ $? == 0 ]; then
        reconstructPar -withZero 2>&1 | tee log.reconstruct
    else
        reconstructPar -newTimes 2>&1 | tee log.reconstruct
    fi

fi

# ----------------------------------------------------------------- end-of-file
