#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

if [ ! -d "0" ]; then
    cp -rp Zero 0
    blockMesh 2>& 1 | tee log.blockMesh
fi

#orderBoundaries -overwrite

if [ ! -d "processor0" ]; then
    decomposePar -copyUniform 2>&1 | tee log.decompose
fi

mpirun -np 8 dissolFoam -parallel 2>&1 | tee log.run

diff 0/C Zero/C > /dev/null 2>&1
if [ $? ]; then
    reconstructPar -withZero 2>&1 | tee log.reconstruct
else
    reconstructPar -newTimes 2>&1 | tee log.reconstruct
fi


# ----------------------------------------------------------------- end-of-file
