#!/bin/sh
cd ${0%/*} || exit 1    # clean case

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf processor* 0
rm -f constant/polyMesh/boundary

# ------------------------------------------------------------------- #
