#!/bin/sh
./Mesh

cd ${0%/*} || exit 1            # run script

if [ ! -d "0" ]; then  # create starting directory
    cp -rp Zero 0
fi

echo "Running in parallel with 4 processors"
if [ ! -d "processor0" ]; then
  decomposePar -copyUniform 2>&1 | tee log.decompose
fi

mpirun -np 4 dissolFoam -parallel 2>&1 | tee log.dissolFoam

reconstructPar -withZero 2>&1 | tee log.reconstruct

# ------------------------------------------------------------------- #
